[video]
startoff = 120000
endoff = 376000
filename = "YI002801.mp4"
blurmask = "blur.svg"

[data.source]
type = "sensordata"
video_off = -247508981
pressure_coeff = 16.0
filename = "YI002801.imu"
format = "sentral-pt"
mag_cal = "../../../calibration/magcal-20190810.bin"
axismap = [1, -3, 2]
calibration = "../../../calibration/2020-03-20/info.calib"

[hud.renderer]
type = "pendulum"
enable_rts_smoother = true
active_row = 9
initial = [0.0, 0.0, 14.5, -0.2, 0.0, 0.0, 0.0]

[hud.renderer.override]
radius = 14.5
orientation_offset = -0.2556

[hud.renderer.stdev]
accel.x = 0.1
accel.y = 0.1
accel.z = 0.1
gyro.x = 0.2
gyro.y = 0.2
gyro.z = 0.2
mag.x = 0.0
mag.y = 0.0
mag.z = 0.0